### ISSUE TITLE
required package apimatic/unirest-php does not exist

### ISSUE THREAD

**Issue by f3cp** [ClickSend/clicksend-php#1]
Trying to install this package but it seems that  the apimatic package for unirest can not be found  

I get this error:
 - clicksend/clicksend-php v3.0 requires apimatic/unirest-php dev-master -> no matching package found.

Should this be updated to another package e.g. mashape/unirest-php

**Comment by matthew-larner** [comment]
thanks for pointing this out. I'll arrange for 'apimatic/unirest-php' to be added.

For now, please try using 'mashape/unirest-php' instead.

**Comment by johndavidson1974** [comment]
I also encountered the same issue earlier. Can you keep me posted once the issue has been fixed?

**Comment by matthew-larner** [comment]
Have you installed composer and run an update?

**Comment by johndavidson1974** [comment]
Running composer update again and the issue is now gone.

Can you share a little bit more on the root cause of the issue? Is that due to apimatic/unirest-php not published to Packagist? Here is a related Tweet https://twitter.com/call_user_func/status/712866549959368705

**Comment by matthew-larner** [comment]
Hi John,

The issue was that 'apimatic/unirest-php' wasn't listed on Packagist - I asked them to add it which has fixed the issue. Thanks for reporting it.

Regards,
Matt
