### ISSUE TITLE
Feature Request - Post Letter History

### ISSUE THREAD

**Issue by ArthurGuy** [ClickSend/clicksend-php#12]
Hi,
The `getPostLetterHistory` method on the `getPostLetter` controller doesn't accept any pagination or ordering/filtering arguments which means it's of very limited value.

The response data includes pagination details but there is no way to access this data through the sdk.

The current implementation means the only data you will ever get back are the oldest 15 letters.

**Comment by matthew-larner** [comment]
Sorry for the delay on this. The new SDK version allows this.
