### ISSUE TITLE
Missing autoload.php file.

### ISSUE THREAD

**Issue by joeyc002** [ClickSend/clicksend-php#16]
The readme says:

Manual Installation
Download the files and include autoload.php:
    require_once('/path/to/clicksend-php/vendor/autoload.php');

This file is missing for those that don't want to use composer.

**Comment by joeyc002** [comment]
I really would rather not have to use console commands to get this to work. I much prefer just being able to include the files I need. 

I did attempt this before with other library's however it created folders I couldn't remove in the end. I don't see the advantage to it.

**Comment by matthew-larner** [comment]
Using composer is by far the most common way of managing packages. If you don't want install and run composer, just download it and include the files you require.

**Comment by joeyc002** [comment]
In the readme, does the "Manual Installation" still mean you need composer then?

**Comment by matthew-larner** [comment]
If you don't user composer you're going to have a bad time. There are multiple dependencies. Plus, if you use composer you can easily keep up to date with the latest packages. We won't be able to support you unless you're using composer like the other 99% of PHP developers out there.

**Comment by joeyc002** [comment]
Bold claim, in my experience, most developers avoid it if they can. 

I won't argue though.

**Comment by SkyEngine-OSP** [comment]
i assume this is still not resolved? i also can't find that `autoload.php` that supposedly found at `/vendor/`, i also refuse to use composer as much as possible. i only want to reference and use the api in my web app as simple as i can.

**Comment by SkyEngine-OSP** [comment]
i think the argument here is that developers are not given the freedom on whether they'd user composer or not - even if its the 99% vs the other 1%.

**Comment by joeyc002** [comment]
I just used require_once on the files that I needed. PHP will give errors about missing classes, just keep manually requiring them until the errors stop. Problem solved.
