### ISSUE TITLE
Exception "Could not resolve host: api.clicksend.local"

### ISSUE THREAD

**Issue by sokoji** [ClickSend/clicksend-php#2]
On localhost I get this exception: Could not resolve host: api.clicksend.local

On dev-server i get not-found error while sending sms and h1 title: "Thank you for visiting Local.com".

I found that there is an error in Configuration.php file.

I will create pull request later.

**Comment by sokoji** [comment]
Check it, please.

It works for me.

**Comment by matthew-larner** [comment]
thanks for pointing this out. I'll push an update.
