### ISSUE TITLE
Where can I download this autoload.php file

### ISSUE THREAD

**Issue by burt00** [ClickSend/clicksend-php#22]

**Comment by jacksegal** [comment]
Hey - the `autoload.php` file is generated by [composer](https://getcomposer.org/)

**Comment by michaelbutler** [comment]
To follow up, have a look at the [README.md](https://github.com/ClickSend/clicksend-php) again. You have to do this:

`composer require clicksend/clicksend-php`

You should run that in the root of your project directory, for example let's say you are in `My Documents/MyProject`.
After running the composer command, it will auto-create `My Documents/MyProject/vendor/autoload.php`.

So let's say you have `My Documents/MyProject/index.php` -- at the top of that you would say `require_once './vendor/autoload.php';`
