### ISSUE TITLE
Dependencies update

### ISSUE THREAD

**Issue by installtech** [ClickSend/clicksend-php#23]
Hi,

Is it possible to update to update Guzzle dependency so the latest version of this library will be compatible with the latest version of Laravel

"guzzlehttp/guzzle": "^6.2" ==> "guzzlehttp/guzzle": "^7.0"

Thanks :)

**Comment by jacksegal** [comment]
[+1!]

**Comment by kasperhartwich** [comment]
As this library is generated by Swagger, they need to update the Swagger Code generator.

**Comment by tshakah** [comment]
Looks like this has been fixed in f0fb100c, but hasn't been pushed to Packagist yet

**Comment by Jaxom-ClickSend** [comment]
Packagist has the dependency updates for this now.
